/**
 * Story 9-5: Voice Input Interface - Comprehensive Coverage
 * 
 * Generated by TEA automate workflow
 * Coverage Strategy: Comprehensive (all ACs)
 * 
 * Test IDs: 9.5-E2E-017 through 9.5-E2E-028
 * Priority: P0 (Critical), P1 (High), P2 (Medium)
 */
import { test, expect, Page, Locator } from '@playwright/test';

const WIDGET_TEST_URL = 'http://localhost:5173/widget-test';

/**
 * Helper: Mock Web Speech API with configurable behavior
 */
async function mockSpeechAPIWithConfig(page: Page, config: {
  supported?: boolean;
  permissionDenied?: boolean;
  noSpeechDetected?: boolean;
  networkError?: boolean;
  simulateInterim?: boolean;
  language?: string;
} = {}): Promise<void> {
  await page.addInitScript((configString) => {
    const cfg = JSON.parse(configString);
    
    if (!cfg.supported) {
      (window as any).SpeechRecognition = undefined;
      (window as any).webkitSpeechRecognition = undefined;
      return;
    }

    class MockSpeechRecognition {
      continuous = false;
      interimResults = true;
      lang = cfg.language || 'en-US';
      onresult: ((event: any) => void | null) = null;
      onerror: ((event: any) => void | null) = null;
      onend: (() => void) | null = null;
      onstart: (() => void) | null = null;

      start() {
        if (cfg.permissionDenied) {
          setTimeout(() => {
            if (this.onerror) {
              this.onerror({ error: 'not-allowed' });
            }
          }, 50);
          return;
        }

        setTimeout(() => {
          if (this.onstart) this.onstart();
        }, 50);

        if (cfg.noSpeechDetected) {
          setTimeout(() => {
            if (this.onerror) {
              this.onerror({ error: 'no-speech' });
            }
            if (this.onend) this.onend();
          }, 200);
          return;
        }

        if (cfg.networkError) {
          setTimeout(() => {
            if (this.onerror) {
              this.onerror({ error: 'network' });
            }
            if (this.onend) this.onend();
          }, 200);
          return;
        }

        if (cfg.simulateInterim) {
          setTimeout(() => {
            if (this.onresult) {
              this.onresult({
                resultIndex: 0,
                results: [
                  {
                    isFinal: false,
                    0: { transcript: 'Hello' }
                  }
                ]
              });
            }
          }, 100);
          
          setTimeout(() => {
            if (this.onresult) {
              this.onresult({
                resultIndex: 0,
                results: [
                  {
                    isFinal: true,
                    0: { transcript: 'Hello world' }
                  }
                ]
              });
            }
            if (this.onend) this.onend();
          }, 300);
        }
      }

      stop() {
        setTimeout(() => {
          if (this.onend) this.onend();
        }, 50);
      }

      abort() {
        setTimeout(() => {
          if (this.onend) this.onend();
        }, 50);
      }
    }

    (window as any).SpeechRecognition = MockSpeechRecognition;
    (window as any).webkitSpeechRecognition = MockSpeechRecognition;
  }, JSON.stringify(config));
}

/**
 * Helper: Open widget and get voice button
 */
async function openWidgetAndGetVoiceButton(page: Page): Promise<Locator> {
  await page.goto(WIDGET_TEST_URL);
  
  const chatBubble = page.getByTestId('chat-bubble');
  await chatBubble.waitFor({ state: 'visible', timeout: 10000 });
  await chatBubble.click();
  
  const voiceButton = page.getByTestId('voice-input-button');
  await voiceButton.waitFor({ state: 'attached', timeout: 10000 });
  return voiceButton;
}

/**
 * Helper: Wait for voice button ready state
 */
async function waitForVoiceButtonReady(button: Locator): Promise<void> {
  await expect(button).toBeEnabled();
  await expect(button).toHaveAttribute('aria-pressed', 'false');
}

/**
 * Helper: Wait for listening state
 */
async function waitForListeningState(button: Locator): Promise<void> {
  await expect(button).toHaveAttribute('aria-pressed', 'true', { timeout: 10000 });
  await expect(button).toHaveClass(/listening/, { timeout: 10000 });
}

/**
 * Helper: Click using JavaScript (bypasses event issues)
 */
async function jsClick(locator: Locator): Promise<void> {
  await locator.evaluate((el) => {
    el.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true }));
  });
}

test.describe('Story 9-5: Voice Input - Comprehensive Coverage', () => {
  
  test.describe('AC8: Permission Denied Error Handling [P0]', () => {
    test('9.5-E2E-017: should show error message when permission denied', async ({ page }) => {
      // Given: Voice input not supported due to permission denial
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        permissionDenied: true 
      });

      // When: User opens widget and clicks voice button
      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await waitForVoiceButtonReady(voiceButton);
      await jsClick(voiceButton);

      // Then: Error message displays with clear explanation
      const errorMessage = page.getByTestId('voice-error-message');
      await expect(errorMessage).toBeVisible({ timeout: 5000 });
      await expect(errorMessage).toContainText(/permission denied|microphone access denied/i);
      
      // And: Fallback to text input is available
      const textInput = page.getByTestId('message-input');
      await expect(textInput).toBeEnabled();
    });

    test('9.5-E2E-018: should provide instructions to enable permissions', async ({ page }) => {
      // Given: Permission denied
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        permissionDenied: true 
      });

      // When: User triggers voice input
      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await jsClick(voiceButton);

      // Then: Instructions for enabling permissions shown
      const instructions = page.getByTestId('voice-permission-instructions');
      await expect(instructions).toBeVisible({ timeout: 5000 });
      await expect(instructions).toContainText(/browser settings|enable microphone/i);
    });

    test('9.5-E2E-019: should allow retry after permission granted', async ({ page }) => {
      // Given: Initial permission denial
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        permissionDenied: true 
      });

      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await jsClick(voiceButton);

      // Error state
      await expect(page.getByTestId('voice-error-message')).toBeVisible();

      // When: User grants permission (simulated by reloading with new config)
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        permissionDenied: false 
      });
      await page.reload();

      // Then: Voice input works after permission granted
      const voiceButtonAfter = await openWidgetAndGetVoiceButton(page);
      await jsClick(voiceButtonAfter);
      await waitForListeningState(voiceButtonAfter);
    });
  });

  test.describe('AC2: Real-Time Speech Recognition Edge Cases [P0]', () => {
    test('9.5-E2E-020: should handle no speech detected gracefully', async ({ page }) => {
      // Given: Voice recognition active but no speech detected
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        noSpeechDetected: true 
      });

      // When: User starts voice input
      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await waitForVoiceButtonReady(voiceButton);
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);

      // Then: No speech error handled gracefully
      const errorMessage = page.getByTestId('voice-error-message');
      await expect(errorMessage).toBeVisible({ timeout: 5000 });
      await expect(errorMessage).toContainText(/no speech detected|didn't hear anything/i);
      
      // And: Voice input returns to idle state
      await expect(voiceButton).toHaveAttribute('aria-pressed', 'false', { timeout: 5000 });
    });

    test('9.5-E2E-021: should handle network error during recognition', async ({ page }) => {
      // Given: Network error during speech recognition
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        networkError: true 
      });

      // When: User starts voice input
      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await waitForVoiceButtonReady(voiceButton);
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);

      // Then: Network error displayed
      const errorMessage = page.getByTestId('voice-error-message');
      await expect(errorMessage).toBeVisible({ timeout: 5000 });
      await expect(errorMessage).toContainText(/network error|connection|offline/i);
    });
  });

  test.describe('AC4: Interim Transcript Display [P1]', () => {
    test('9.5-E2E-022: should display interim transcript with distinct visual style', async ({ page }) => {
      // Given: Voice recognition with interim results
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        simulateInterim: true 
      });

      // When: User starts voice input
      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await waitForVoiceButtonReady(voiceButton);
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);

      // Then: Interim transcript displays with gray italic style
      const interimTranscript = page.getByTestId('voice-interim-transcript');
      await expect(interimTranscript).toBeVisible({ timeout: 1000 });
      await expect(interimTranscript).toContainText('Hello');
      
      // Verify visual style
      const fontStyle = await interimTranscript.evaluate((el) => {
        const styles = window.getComputedStyle(el);
        return {
          fontStyle: styles.fontStyle,
          color: styles.color
        };
      });
      expect(fontStyle.fontStyle).toBe('italic');
    });

    test('9.5-E2E-023: should transition interim to final transcript smoothly', async ({ page }) => {
      // Given: Voice recognition with interim → final flow
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        simulateInterim: true 
      });

      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await waitForVoiceButtonReady(voiceButton);
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);

      // When: Final transcript arrives
      await page.waitForTimeout(400); // Allow final transcript to arrive

      // Then: Final transcript in input field
      const messageInput = page.getByTestId('message-input');
      await expect(messageInput).toHaveValue('Hello world');
      
      // And: Interim transcript no longer visible
      const interimTranscript = page.getByTestId('voice-interim-transcript');
      await expect(interimTranscript).not.toBeVisible({ timeout: 1000 });
    });
  });

  test.describe('AC5: Final Transcript to Input [P1]', () => {
    test('9.5-E2E-024: should populate input field with final transcript', async ({ page }) => {
      // Given: Voice recognition completes
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        simulateInterim: true 
      });

      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await waitForVoiceButtonReady(voiceButton);
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);

      // When: Final transcript arrives
      await page.waitForTimeout(400);

      // Then: Input field populated with final transcript
      const messageInput = page.getByTestId('message-input');
      await expect(messageInput).toHaveValue('Hello world');
    });

    test('9.5-E2E-025: should allow user to edit transcript before sending', async ({ page }) => {
      // Given: Final transcript in input field
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        simulateInterim: true 
      });

      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);
      await page.waitForTimeout(400);

      const messageInput = page.getByTestId('message-input');
      await expect(messageInput).toHaveValue('Hello world');

      // When: User edits the text
      await messageInput.fill('Hello world edited');

      // Then: Editable text preserved
      await expect(messageInput).toHaveValue('Hello world edited');
      
      // And: Send button enabled
      const sendButton = page.getByTestId('send-message-button');
      await expect(sendButton).toBeEnabled();
    });

    test('9.5-E2E-026: should enable send button after transcript ready', async ({ page }) => {
      // Given: No transcript initially
      await mockSpeechAPIWithConfig(page, { supported: true });

      const voiceButton = await openWidgetAndGetVoiceButton(page);
      const sendButton = page.getByTestId('send-message-button');
      
      // Initially: Send button disabled
      await expect(sendButton).toBeDisabled();

      // When: Final transcript arrives
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        simulateInterim: true 
      });
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);
      await page.waitForTimeout(400);

      // Then: Send button enabled
      await expect(sendButton).toBeEnabled();
    });
  });

  test.describe('AC6: Multiple Language Support [P2]', () => {
    test('9.5-E2E-027: should support configured language for recognition', async ({ page }) => {
      // Given: Widget configured for Spanish
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        language: 'es-ES',
        simulateInterim: true 
      });

      // When: User uses voice input
      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await waitForVoiceButtonReady(voiceButton);
      await jsClick(voiceButton);
      await waitForListeningState(voiceButton);

      // Then: Recognition uses Spanish language
      const recognitionLang = await voiceButton.evaluate(() => {
        const recognition = (window as any).__lastSpeechRecognition;
        return recognition?.lang;
      });
      expect(recognitionLang).toBe('es-ES');
    });

    test('9.5-E2E-028: should store language preference', async ({ page }) => {
      // Given: User selects language preference
      await mockSpeechAPIWithConfig(page, { supported: true });

      // When: User changes language setting
      const voiceButton = await openWidgetAndGetVoiceButton(page);
      
      // Check if language selector exists
      const languageSelector = page.getByTestId('voice-language-selector');
      if (await languageSelector.count() > 0) {
        await languageSelector.selectOption('es-ES');
        
        // Then: Preference stored in localStorage
        const storedLang = await page.evaluate(() => {
          return localStorage.getItem('widget-voice-language');
        });
        expect(storedLang).toBe('es-ES');
      }
    });
  });

  test.describe('Error Recovery [P1]', () => {
    test('9.5-E2E-029: should recover from error and allow retry', async ({ page }) => {
      // Given: Error occurred
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        noSpeechDetected: true 
      });

      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await jsClick(voiceButton);

      // Error state
      await expect(page.getByTestId('voice-error-message')).toBeVisible();

      // When: User clicks retry
      const retryButton = page.getByTestId('voice-retry-button');
      if (await retryButton.count() > 0) {
        await retryButton.click();
        
        // Then: Returns to idle state, ready for new attempt
        await waitForVoiceButtonReady(voiceButton);
      }
    });

    test('9.5-E2E-030: should clear error when starting new recognition', async ({ page }) => {
      // Given: Previous error displayed
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        noSpeechDetected: true 
      });

      const voiceButton = await openWidgetAndGetVoiceButton(page);
      await jsClick(voiceButton);
      await expect(page.getByTestId('voice-error-message')).toBeVisible();

      // When: User starts new recognition attempt
      await mockSpeechAPIWithConfig(page, { 
        supported: true, 
        simulateInterim: true 
      });
      await jsClick(voiceButton);

      // Then: Error cleared
      const errorMessage = page.getByTestId('voice-error-message');
      await expect(errorMessage).not.toBeVisible({ timeout: 2000 });
    });
  });
});
