/**
 * Chat Widgets Demo Component
 * Feature tabs and description for chat widget demos
 */

import * as React from 'react';
import { styles } from './styles';
import { MockChatWindow } from './MockChatWindow';

type FeatureId = 'sources' | 'faq' | 'replies' | 'feedback' | 'contact';

interface FeatureInfo {
  id: FeatureId;
  name: string;
  icon: string;
  title: string;
  description: string;
  implementation: string;
}

const features: FeatureInfo[] = [
  {
    id: 'sources',
    name: 'Source Citations',
    icon: '📚',
    title: 'Source Citations Widget',
    description: 'Display RAG source documents with expandable snippets. Shows users where information comes from, building trust and enabling deeper exploration.',
    implementation: 'Backend: Extract chunk metadata from RAG retrieval. Frontend: Clickable cards that expand to show document snippets.',
  },
  {
    id: 'faq',
    name: 'FAQ Chips',
    icon: '💬',
    title: 'FAQ Quick Buttons Widget',
    description: 'Show related FAQs as clickable chips. Users can quickly ask common questions without typing, improving engagement and reducing friction.',
    implementation: 'Backend: Match user query against FAQ keywords. Frontend: Render chips that send questions when clicked.',
  },
  {
    id: 'replies',
    name: 'Quick Replies',
    icon: '⚡',
    title: 'Quick Reply Chips Widget',
    description: 'Suggested follow-up questions generated by the LLM. Guides conversation flow and helps users discover relevant topics.',
    implementation: 'Backend: LLM generates 2-3 suggested replies. Frontend: Chips that send the suggested question.',
  },
  {
    id: 'feedback',
    name: 'Feedback',
    icon: '👍',
    title: 'Feedback Rating Widget',
    description: 'Simple thumbs up/down rating on bot responses. Collects user satisfaction data to improve response quality over time.',
    implementation: 'Backend: Store feedback in message_feedback table. Frontend: Rating buttons with confirmation toast.',
  },
  {
    id: 'contact',
    name: 'Contact Card',
    icon: '📞',
    title: 'Contact Card Widget',
    description: 'Display contact options when users need human help. Shows email, phone, and live chat options with business hours.',
    implementation: 'Backend: Contact options from merchant config. Frontend: Clickable buttons that open contact channels.',
  },
];

interface ChatWidgetsDemoProps {
  theme: 'light' | 'dark' | 'auto';
}

export function ChatWidgetsDemo({ theme }: ChatWidgetsDemoProps) {
  const [activeFeature, setActiveFeature] = React.useState<FeatureId>('sources');

  const currentFeature = features.find(f => f.id === activeFeature) || features[0];

  return (
    <div style={{ display: 'flex', gap: '24px', flex: 1 }}>
      {/* Feature Tabs */}
      <div style={styles.featureTabs}>
        <div style={{ fontSize: '12px', fontWeight: 600, color: '#6b7280', marginBottom: '12px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
          Chat Widgets
        </div>
        {features.map((feature) => (
          <button
            key={feature.id}
            style={{
              ...styles.featureTab,
              backgroundColor: activeFeature === feature.id ? '#eef2ff' : 'transparent',
              color: activeFeature === feature.id ? '#4f46e5' : '#374151',
            }}
            onClick={() => setActiveFeature(feature.id)}
            onMouseEnter={(e) => {
              if (activeFeature !== feature.id) {
                e.currentTarget.style.backgroundColor = '#f9fafb';
              }
            }}
            onMouseLeave={(e) => {
              if (activeFeature !== feature.id) {
                e.currentTarget.style.backgroundColor = 'transparent';
              }
            }}
          >
            <span style={{ fontSize: '18px' }}>{feature.icon}</span>
            <span>{feature.name}</span>
          </button>
        ))}
        
        {/* Implementation Notes */}
        <div style={{ marginTop: '24px', padding: '16px', backgroundColor: '#f0fdf4', borderRadius: '8px', border: '1px solid #bbf7d0' }}>
          <div style={{ fontSize: '12px', fontWeight: 600, color: '#166534', marginBottom: '8px' }}>
            ✅ Ready to Implement
          </div>
          <div style={{ fontSize: '11px', color: '#15803d', lineHeight: 1.5 }}>
            All widgets have existing backend infrastructure (FAQ model, RAG service, conversation service) that can be extended.
          </div>
        </div>
      </div>

      {/* Mock Chat Window */}
      <MockChatWindow feature={activeFeature} theme={theme} />

      {/* Feature Description */}
      <div style={{ width: '320px', flexShrink: 0 }}>
        <div style={styles.descriptionBox}>
          <h3 style={styles.descriptionTitle}>
            <span>{currentFeature.icon}</span>
            {currentFeature.title}
          </h3>
          <p style={styles.descriptionText}>{currentFeature.description}</p>
        </div>

        <div style={{ ...styles.descriptionBox, marginTop: '16px' }}>
          <h4 style={{ fontSize: '14px', fontWeight: 600, color: '#374151', marginBottom: '8px' }}>
            Implementation
          </h4>
          <p style={{ fontSize: '12px', color: '#6b7280', lineHeight: 1.6 }}>
            {currentFeature.implementation}
          </p>
        </div>

        <div style={{ ...styles.descriptionBox, marginTop: '16px', backgroundColor: '#eff6ff', border: '1px solid #bfdbfe' }}>
          <h4 style={{ fontSize: '14px', fontWeight: 600, color: '#1e40af', marginBottom: '8px' }}>
            🎯 Try These Interactions
          </h4>
          <ul style={{ margin: 0, padding: '0 0 0 16px', fontSize: '12px', color: '#1e40af', lineHeight: 1.8 }}>
            {activeFeature === 'sources' && (
              <>
                <li>Click a source card to expand</li>
                <li>Hover to see hover effect</li>
                <li>Notice document type icons</li>
              </>
            )}
            {activeFeature === 'faq' && (
              <>
                <li>Click an FAQ chip to send</li>
                <li>Watch bot respond with answer</li>
                <li>See suggested replies appear</li>
              </>
            )}
            {activeFeature === 'replies' && (
              <>
                <li>Click a suggested reply</li>
                <li>Continue the conversation</li>
                <li>Type your own message too</li>
              </>
            )}
            {activeFeature === 'feedback' && (
              <>
                <li>Click thumbs up or down</li>
                <li>See confirmation toast</li>
                <li>Count updates in real-time</li>
              </>
            )}
            {activeFeature === 'contact' && (
              <>
                <li>Click any contact option</li>
                <li>See toast notification</li>
                <li>Notice business hours info</li>
              </>
            )}
          </ul>
        </div>
      </div>
    </div>
  );
}
