"""Messenger-specific personality templates for message_processor.py (Story 11-5, AC8).

Registered via PersonalityAwareResponseFormatter.register_response_type().
All 3 personality variants must be defined for each key to prevent KeyError.
"""

from app.models.merchant import PersonalityType
from app.services.personality.response_formatter import PersonalityAwareResponseFormatter

MESSENGER_TEMPLATES = {
    PersonalityType.FRIENDLY: {
        "greeting": "Hi! How can I help you today? 😊",
        "error": "Oops, something went wrong! 😅 Please try again.",
        "unavailable": "I'm taking a quick break! 😊 Please try again in a moment or contact support.",
        "welcome_back": "Welcome back! You have {item_count} item{s} in your cart. Type 'cart' to view! 👋",
        "no_product": "I'm not sure which product you mean! 😅 Want to search for products first?",
        "product_not_found": "Hmm, I couldn't find that product. 🤔 Want to try searching again?",
        "variant_unavailable": "Sorry, that variant isn't available right now. 😕",
        "out_of_stock": "Sorry, '{title}' is out of stock right now. 😕 Want to check out similar items?",
        "cart_add_error": "Oops, I had trouble adding that to your cart! 😅 Please try again.",
        "cart_confirm": "Added {title} (${price}) to your cart! 🛒 View cart: [View Cart] button or type 'cart'",
        "cart_view_error": "Sorry, I couldn't load your cart. 😅 Please try again!",
        "cart_remove_error": "Oops, I had trouble removing that item. 😅 Please try again!",
        "cart_quantity_error": "Sorry, I couldn't update the quantity. 😅 Please try again!",
        "checkout_error": "Oops, something went wrong during checkout! 😅 Please try again.",
        "order_error": "Sorry, I couldn't look up your order right now. 😅 Please try again!",
        "fallback": "I'm not sure what you're looking for. 🤔 Could you tell me a bit more?",
        "handoff": "Connecting you with a human agent! 😊 They'll be with you shortly.",
        "postback_continue": "What else can I help you find? 😊 Type a product or category!",
        "postback_browse": "What category of products are you interested in? 😊",
        "postback_search": "What would you like to search for? 🔍",
        "postback_unknown": "Hmm, I didn't catch that. 😅 Could you try again?",
        "cart_removed": "Removed {item} from your cart.",
        "cart_removed_empty": "Your cart is now empty. Let's find some more products! 🛍️",
        "forget_success": "I've forgotten your cart and preferences. Your order references are kept for business purposes. 👍",
        "forget_error": "Sorry, I couldn't clear your data. 😅 Please try again.",
        "consent_prompt": "To remember your cart for next time, I'll save it. OK? 😊",
        "consent_yes": "Yes, save my cart",
        "consent_no": "No, don't save",
        "consent_added": "Great! I've added {title} (${price}) to your cart. Your cart will be saved for 24 hours! 🎉",
        "consent_expired": "Your cart session expired. 😕 Please search for the product again!",
        "consent_granted": "Thanks! I'll save your cart for next time. 😊 What would you like to add?",
        "consent_denied": "No worries! I won't save your cart. You can still shop, but your cart will be cleared when you close this chat. 👍",
        "consent_add_error": "Oops, I had trouble adding that item. 😅 Please try again!",
    },
    PersonalityType.PROFESSIONAL: {
        "greeting": "Hello. How may I assist you today?",
        "error": "An error occurred. Please try your request again.",
        "unavailable": "I am currently unavailable. Please contact support or try again later.",
        "welcome_back": "Welcome back. You have {item_count} item{s} in your cart. Type 'cart' to view.",
        "no_product": "I do not have a product reference. Please search for products first.",
        "product_not_found": "I was unable to locate that product. Please try your search again.",
        "variant_unavailable": "That product variant is not currently available.",
        "out_of_stock": "'{title}' is currently out of stock.",
        "cart_add_error": "An error occurred while adding the item to your cart. Please try again.",
        "cart_confirm": "{title} (${price}) has been added to your cart. View cart: [View Cart] button or type 'cart'",
        "cart_view_error": "Unable to retrieve cart contents. Please try again.",
        "cart_remove_error": "Unable to remove the item from your cart. Please try again.",
        "cart_quantity_error": "Unable to update the quantity. Please try again.",
        "checkout_error": "An error occurred during checkout. Please try again.",
        "order_error": "Unable to look up your order at this time. Please try again.",
        "fallback": "I am not certain what you are looking for. Could you provide more details?",
        "handoff": "Connecting you with a human agent. They will be with you shortly.",
        "postback_continue": "What else may I help you find? Please type a product or category.",
        "postback_browse": "What category of products are you interested in?",
        "postback_search": "What would you like to search for?",
        "postback_unknown": "I did not understand that action. Please try again.",
        "cart_removed": "{item} has been removed from your cart.",
        "cart_removed_empty": "Your cart is now empty. Would you like to browse our products?",
        "forget_success": "Your cart and preferences have been cleared. Order references are retained for business purposes.",
        "forget_error": "Unable to clear your data at this time. Please try again.",
        "consent_prompt": "To save your cart for your next visit, I will store it. Is this acceptable?",
        "consent_yes": "Yes, save my cart",
        "consent_no": "No, do not save",
        "consent_added": "{title} (${price}) has been added to your cart. Your cart will be saved for 24 hours.",
        "consent_expired": "Your session has expired. Please search for the product again.",
        "consent_granted": "Thank you. Your cart will be saved for your next visit. What would you like to add?",
        "consent_denied": "Understood. Your cart will not be saved. It will be cleared when this chat closes.",
        "consent_add_error": "An error occurred while adding the item. Please try again.",
    },
    PersonalityType.ENTHUSIASTIC: {
        "greeting": "Hey there! 🎉 How can I help you today?!",
        "error": "Oopsie! Something went a little wonky! 😅 Let's try again! 💪",
        "unavailable": "I'm taking a tiny break! 😊 Please try again in just a moment! ✨",
        "welcome_back": "WELCOME BACK!!! 🎉 You have {item_count} item{s} in your cart! Type 'cart' to see them! 🛍️",
        "no_product": "Hmm, I'm not sure which AWESOME product you mean! 😅 Let's search for it first! 🔍",
        "product_not_found": "Oh no! I couldn't find that product! 😢 Let's try searching again! 💪",
        "variant_unavailable": "Aww, that variant isn't available right now! 😢 But there are SO many other great options! ✨",
        "out_of_stock": "Oh no! '{title}' is out of stock! 😢 But don't worry - let's find something even BETTER! 🔥",
        "cart_add_error": "Oops! I had a little trouble adding that to your cart! 😅 Let's try again! 🛒",
        "cart_confirm": "WOOHOO! {title} (${price}) is now in your cart! 🛒 View cart: [View Cart] button or type 'cart'!",
        "cart_view_error": "Hmm, I couldn't load your cart! 😅 Let's try again! 🛒",
        "cart_remove_error": "Oops! I had trouble removing that item! 😅 Let's try again! ✨",
        "cart_quantity_error": "Oops! I couldn't update the quantity! 😅 Let's try again! 💪",
        "checkout_error": "Eek! Checkout hit a tiny bump! 😅 Let's try again - you're SO close! ✨",
        "order_error": "Hmm, I couldn't find your order right now! 😅 Let's try again! 🔍",
        "fallback": "I'm not sure what you're looking for! 🤔 Could you tell me more? I'm SO here to help!!!",
        "handoff": "Connecting you with a SUPER helpful human agent! 😊 They'll be with you in a flash! ✨",
        "postback_continue": "What else can I help you find?! 🎉 Type a product or category! I'm ready! 🔥",
        "postback_browse": "What category of products are you interested in?! 😊 SO many options! ✨",
        "postback_search": "What would you like to search for?! 🔍 I can't wait to help you find something AMAZING!",
        "postback_unknown": "Hmm, I didn't quite catch that! 😅 Could you try again? I'm all ears! 👂",
        "cart_removed": "Removed {item} from your cart! ✨",
        "cart_removed_empty": "Your cart is empty now! 🛍️ Let's fill it with something AMAZING! 🔥",
        "forget_success": "All cleared! ✨ Your order references are kept for business purposes. What's next?! 🎉",
        "forget_error": "Oops! I couldn't clear your data right now! 😅 Let's try again! 💪",
        "consent_prompt": "Want me to save your cart for next time?! I'll keep it safe! 😊 Is that OK?",
        "consent_yes": "Yes, save my cart! 🎉",
        "consent_no": "No thanks",
        "consent_added": "AMAZING! {title} (${price}) is in your cart! 🛒 I'll save it for 24 hours! ✨",
        "consent_expired": "Oh no! Your session expired! 😢 Please search for the product again! 💪",
        "consent_granted": "YAY! I'll save your cart for next time! 🎉 What would you like to add?!",
        "consent_denied": "No worries at all! 😊 Your cart won't be saved, but you can still shop! Let's find something AWESOME! 🔥",
        "consent_add_error": "Oops! I had trouble adding that! 😅 Let's try again! 💪",
    },
}


def register_messenger_templates() -> None:
    """Register messenger personality templates with the formatter."""
    PersonalityAwareResponseFormatter.register_response_type("messenger", MESSENGER_TEMPLATES)
